language: php

php:
  - 7.0
  - 7.1
  - 7.2

install:
  - printf "\n" | pecl install -f swoole-4.2.8

before_script:
  - composer install --dev
  - php -v
  - php -m

script:
  - vendor/bin/phpcs
  - tests/run