language: php

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.2
      env: LINT=true
    - php: 7.2
      env: PHAR=true

install:
  - printf "\n" | pecl install -f swoole-4.2.8

before_script:
  - composer install --no-dev
  - php -v
  - php -m

script:
  - |
    if [[ $LINT != "" ]]; then
      composer install --dev
      vendor/bin/phpcs
    elif [[ $PHAR != "" ]]; then
      composer install --dev
      vendor/bin/box compile
      ./SMProxy.phar
    else
      chmod a+x bin/SMProxy
      tests/run
    fi